### ISSUE TITLE
Embedding learnr in shiny app

### ISSUE THREAD

**Issue by ghost** [gadenbuie/shinyComponents#10]
Thanks for this great package. Can shinycomponents be used for embedding learnr rmarkdown doc in Shiny? I tried but it returns this error - **_Error: Tutorial exercises require the use of 'runtime: shiny_prerendered'_**

**Comment by gadenbuie** [comment]
Hi thanks for the question -- unfortunately, shinyComponents isn't really designed for this. Rather, it's for creating pieces of a shiny app that you can use and re-use in other shiny apps.

I've learned a lot from learnr but it's a very different approach 😄
